minimumReleaseAge: 1440 # 1 day
shellEmulator: true
allowBuilds:
  esbuild: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - '@trickfilm400/rollup-plugin-off-main-thread@3.0.0-pre1'
trustPolicyIgnoreAfter: 262980 # 6 months
minimumReleaseAgeExclude:
  # Renovate security update: maplibre-gl@6.4.1
  - maplibre-gl@6.4.1
